# Generated by Django 3.1.4 on 2022-05-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicit_symtpom', models.CharField(max_length=200)),
                ('implicit_symtpom', models.CharField(max_length=200)),
                ('disease_tag', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
