# Generated by Django 3.1.4 on 2022-05-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='explicit_symtpom',
            new_name='explicit_symptom',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='implicit_symtpom',
            new_name='implicit_symptom',
        ),
    ]
